import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'
import { createVerify, createHmac } from 'crypto'
import { app } from 'electron'
import machineIdPkg from 'node-machine-id'
const { machineId: getMachineIdLib } = machineIdPkg

const __filename = fileURLToPath(import.meta.url)
const __dirname = path.dirname(__filename)

// Public key for license verification. Replace with your own public key generated by gen-key.js
// A starter keypair will be created by gen-key.js into assets/private.pem & assets/public.pem
let PUBLIC_KEY = null
try {
  PUBLIC_KEY = fs.readFileSync(path.join(__dirname, 'assets', 'public.pem'), 'utf-8')
} catch {
  // fallback sample (will be replaced when you run gen-key.js)
  PUBLIC_KEY = `-----BEGIN PUBLIC KEY-----\nMFwwDQYJKoZIhvcNAQEBBQADSwAwSAJBAN1oHcCvl4l2xwqHqg3A8e8M+0Kk6Jub\n1yQ7z+eXwXn0QzRFGQk0m8aQCMbqz5G2k3GgZC3aP1yYy0sJ8Wg1a+ECAwEAAQ==\n-----END PUBLIC KEY-----`
}

// Secret for short license verification (created by gen-key.js if missing)
let SHORT_SECRET = null
try {
  SHORT_SECRET = fs.readFileSync(path.join(__dirname, 'assets', 'short-secret.txt'), 'utf-8').trim()
} catch {}

function base64urlDecode(str){
  str = str.replace(/-/g,'+').replace(/_/g,'/')
  const pad = str.length % 4
  if (pad) str += '='.repeat(4-pad)
  return Buffer.from(str, 'base64').toString('utf-8')
}

export async function getMachineId(){
  // Use hashed machine id (no admin privilege required)
  const id = await getMachineIdLib()
  return id
}

export async function ensureActivated(licenseKey, machineId){
  try {
    const payload = await verifyLicense(licenseKey, machineId)
    return !!payload
  } catch {
    return false
  }
}

export async function verifyAndSaveActivation(licenseKey, machineId){
  const payload = await verifyLicense(licenseKey, machineId)
  if (!payload) return false
  const userData = app.getPath('userData')
  const file = path.join(userData, 'activation.json')
  fs.mkdirSync(userData, { recursive: true })
  fs.writeFileSync(file, JSON.stringify({ licenseKey, boundTo: machineId, payload }, null, 2))
  return true
}

export async function verifyLicense(licenseKey, machineId){
  if (!licenseKey || typeof licenseKey !== 'string') return null

  // 1) Short universal key path: SK-XXXX-XXXX-XXXX-XXXX (Base32, with HMAC checksum)
  if (/^\s*SK-[A-Z2-7]{4}(?:-[A-Z2-7]{4}){3}\s*$/i.test(licenseKey)) {
    if (!SHORT_SECRET) return null
    const normalized = licenseKey.trim().toUpperCase()
    const body = normalized.replace(/^SK-/, '')
    const compact = body.replace(/-/g, '') // 16 chars base32: 12 rand + 4 checksum
    const rand = compact.slice(0, 12)
    const checksum = compact.slice(12)
    // Compute checksum = first 4 Base32 of HMAC(rand)
    const h = createHmac('sha256', SHORT_SECRET)
    h.update(rand)
    const digest = h.digest()
    const alphabet = 'ABCDEFGHIJKLMNOPQRSTUVWXYZ234567'
    // Map first 20 bits of digest to 4 Base32 chars
    let bits = (digest[0] << 12) | (digest[1] << 4) | (digest[2] >> 4)
    const calc = [
      alphabet[(bits >> 15) & 31],
      alphabet[(bits >> 10) & 31],
      alphabet[(bits >> 5) & 31],
      alphabet[bits & 31],
    ].join('')
    if (calc !== checksum) return null
    return { type: 'short', rand, iat: Date.now() }
  }

  // 2) RSA signed license format: base64url(json).base64url(signature)
  if (!licenseKey.includes('.')) return null
  const [b64, sigB64] = licenseKey.split('.')
  try {
    const json = base64urlDecode(b64)
    const payload = JSON.parse(json)
    // Check expiry
    if (payload.exp && Date.now() > Number(payload.exp)) return null
    // If bound to machine, verify
    if (payload.mid && payload.mid !== machineId) return null

    const verifier = createVerify('RSA-SHA256')
    verifier.update(b64)
    verifier.end()
    const sig = Buffer.from(sigB64.replace(/-/g,'+').replace(/_/g,'/'), 'base64')
    const ok = verifier.verify(PUBLIC_KEY, sig)
    if (!ok) return null
    return payload
  } catch {
    return null
  }
}
